In [1]:
import pandas as pd

path = "CleanPlayerData.csv"
data = pd.read_csv(path)
data.head()

,person,Alignment,fOutcome,Hit1,HitL,HitNum,Death,Inactive,GM,Mod,Spec,gtype,GameNum,Game,Broken,Role
0,Meta,0,0,-,-,-,NaN,N,Y,N,N,LG,1.0,LG1,N,GM
1,Cracknut,G,L,1.0,1.0,1.0,E,N,N,N,N,LG,1.0,LG1,N,Tineye
2,Edgedancer,G,L,2.0,2.0,1.0,L,N,N,N,N,LG,1.0,LG1,N,Cop
3,Mailliw73,G,L,4.0,4.0,1.0,L,N,N,N,N,LG,1.0,LG1,N,Regular
4,Aether,E,W,4.0,4.0,1.0,V,N,N,N,N,LG,1.0,LG1,N,Smoker