In [7]:
# imports
import pandas as pd

In [8]:
# load data
player_path = "DataTest.csv"
playerdata = pd.read_csv(player_path)
playerdata.head()

,ID,Player,Alignment,Faction Outcome,First Hit,Last Hit,# of Hits,Death/\n Survival,Inactive,GM,...,Broken,Role,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,1,Meta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,...,NaN,GM,Roles that are unique and don't fit,NaN,Unfinished,Alignment,Victory,Hits,Survival,NaN
1,2,Cracknut,G,L,1.0,1.0,1.0,E,NaN,NaN,...,NaN,Tineye,MR1/LG8/MR7 need work,NaN,QF7,0,0,13,0,NaN
2,3,Edgedancer,G,L,2.0,2.0,1.0,L,NaN,NaN,...,NaN,Cop,NaN,NaN,MR6,0,0,25,0,NaN
3,4,Mailliw73,G,L,4.0,4.0,1.0,L,NaN,NaN,...,NaN,Regular,NaN,NaN,LG12,0,0,2,0,NaN
4,5,Aether,E,W,4.0,4.0,1.0,V,NaN,NaN,...,NaN,Smoker,NaN,NaN,QF8,0,0,22,0,NaN

In [9]:
# Select useful columns (last few are irrelevant)
pdata = playerdata[["Player", "Alignment", "Faction Outcome", "First Hit", "Last Hit", "# of Hits", 
             "Death/\n Survival", "Inactive", 'GM', 'Mod', 'Spec', 'Game Type', 'Game #', 
             'Unnamed: 14', 'Broken', 'Role']]

# Rename columns for accuracy or simplicity
pdata = pdata.rename(columns = {"Player": "person","Faction Outcome": "fOutcome", "First Hit": "Hit1", "Last Hit": "HitL",
                       "# of Hits": "HitNum", "Death/\n Survival": "Death", "Game Type": "gtype",
                       "Game #": "GameNum", "Unnamed: 14": "Game"})

In [10]:
# Fill in NaN values
pdata = pdata.fillna({"Alignment": 0, 
                       "fOutcome": 0, 
                      "Hit1": "-", 
                      "HitL": "-", 
                      "HitNum": "-", 
                      "Inactive":"N", 
                      "GM":"N", 
                      "Mod": "N", 
                      "Spec": "N", 
                      "Broken": "N", 
                      "Role": "-"})

In [11]:
pdata.to_csv("CleanPlayerData.csv", index = False)

In [12]:
pdata.head()

,person,Alignment,fOutcome,Hit1,HitL,HitNum,Death,Inactive,GM,Mod,Spec,gtype,GameNum,Game,Broken,Role
0,Meta,0,0,-,-,-,NaN,N,Y,N,N,LG,1.0,LG1,N,GM
1,Cracknut,G,L,1,1,1,E,N,N,N,N,LG,1.0,LG1,N,Tineye
2,Edgedancer,G,L,2,2,1,L,N,N,N,N,LG,1.0,LG1,N,Cop
3,Mailliw73,G,L,4,4,1,L,N,N,N,N,LG,1.0,LG1,N,Regular
4,Aether,E,W,4,4,1,V,N,N,N,N,LG,1.0,LG1,N,Smoker